ACR validation added to deployment pipeline...

diff --git a/.github/workflows/docker-image-to-acr.yml b/.github/workflows/docker-image-to-acr.yml
--- a/.github/workflows/docker-image-to-acr.yml
+++ b/.github/workflows/docker-image-to-acr.yml
@@ -6,7 +6,7 @@ on:
       - main
 
 jobs:
-  Build:
+  Build-and-Push:
     runs-on: ubuntu-latest
 
     steps:
@@ -19,6 +19,10 @@ jobs:
         username:       ${{ secrets.AZURE_REGISTRY_USERNAME }}
         password:       ${{ secrets.AZURE_REGISTRY_PASSWORD }}
 
+    - name: Check if login was successful
+      run: |
+        docker pull ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/hello-world:latest || echo "Login failed or image does not exist"
+    
     - name: Build and Push Docker image
       run: |
         docker build . -t   ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/pseudobank-frontend:latest
