keep working on deploy to acr

diff --git a/.github/workflows/docker-image-to-acr.yml b/.github/workflows/docker-image-to-acr.yml
--- a/.github/workflows/docker-image-to-acr.yml
+++ b/.github/workflows/docker-image-to-acr.yml
@@ -12,18 +12,29 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
+    - name: 'Login via Azure CLI'
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.AZURE_REGISTRY_SP_CREDS }}
+      
     - name: Log in to Azure Container Registry
       uses: azure/docker-login@v1
       with:
-        login-server:   ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
+        login-server:   ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
         username:       ${{ secrets.AZURE_REGISTRY_USERNAME }}
         password:       ${{ secrets.AZURE_REGISTRY_PASSWORD }}
 
     - name: Check if login was successful
       run: |
-        docker pull ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/hello-world:latest || echo "Login failed or image does not exist"
+        set -e
+        docker pull ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/hello-world:latest || echo "Login failed or image does not exist"
     
-    - name: Build and Push Docker image
+    - name: Build Docker image
       run: |
-        docker build . -t   ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/pseudobank-frontend:latest
-        docker push         ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/pseudobank-frontend:latest
+        docker build . -t   ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/pseudobank-frontend:latest
+        docker push         ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/pseudobank-frontend:latest
+
+    - name: Push Docker image to ACR
+      run: |
+        docker push         ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/pseudobank-frontend:latest
+  
