fix pipeline

diff --git a/.github/workflows/docker-image-to-acr.yml b/.github/workflows/docker-image-to-acr.yml
--- a/.github/workflows/docker-image-to-acr.yml
+++ b/.github/workflows/docker-image-to-acr.yml
@@ -20,20 +20,20 @@ jobs:
     - name: Log in to Azure Container Registry
       uses: azure/docker-login@v1
       with:
-        login-server:   ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
+        login-server:   ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io
         username:       ${{ secrets.AZURE_REGISTRY_USERNAME }}
         password:       ${{ secrets.AZURE_REGISTRY_PASSWORD }}
 
     - name: Check if login was successful
       run: |
         set -e
-        docker pull ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/hello-world:latest || echo "Login failed or image does not exist"
+        docker pull ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/hello-world:latest || echo "Login failed or image does not exist"
     
     - name: Build Docker image
       run: |
         docker build . --build-arg REACT_APP_JUICYSCORE_DATA_API_KEY=${{ secrets.REACT_APP_JUICYSCORE_DATA_API_KEY }} \
-            -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/pseudobank-frontend:latest
-        docker push         ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/pseudobank-frontend:latest
+            -t ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/pseudobank-frontend:latest
+        docker push         ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/pseudobank-frontend:latest
 
     - name: Push Docker image to ACR
       run: |
@@ -52,7 +52,7 @@ jobs:
     - name: Deploy to Azure Container App
       uses: azure/container-apps-deploy-action@v0
       with:
-        acrName: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
+        acrName: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}
         containerAppName: ${{ vars.AZ_CONTAINER_APP_NAME }}
         resourceGroup: ${{ vars.AZ_RESOURCE_GROUP }}
-        imageToDeploy: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/pseudobank-frontend:latest
+        imageToDeploy: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/pseudobank-frontend:latest
